[build]
  command = "npm run build"
  publish = "dist"

# Ако отворят employerapp.netlify.app → прати към /company
[[redirects]]
  from = "/"
  to   = "/company"
  status = 301

# SPA fallback за всичко под /company
[[redirects]]
  from = "/company"
  to   = "/index.html"
  status = 200

[[redirects]]
  from = "/company/*"
  to   = "/index.html"
  status = 200
